def inputTagVersion = env.TAG_VERSION.trim()
def inputTagComment = env.TAG_COMMENT.trim()
def inputDevProject = env.DEV_PROJECT.trim()

def config_Component = "react" 

pipeline {
  agent {
    label 'nodejs-18'
  }
  stages {
    stage('Manage Source Tag') {
      steps {
        script {
          openshift.withCluster() {
            withCredentials([usernamePassword(credentialsId: "${inputDevProject}-basic-auth-code-repo-read-write-secret-react", usernameVariable: "GITLAB_USER", passwordVariable: "GITLAB_PWD")]) {
              if (inputTagVersion.isEmpty()) {
                error('Please set non-empty environment variable TAG_VERSION!')
              }
              git branch: 'master', url: "https://${GITLAB_USER}:${GITLAB_PWD}@fhkgitlab.fhk.app/bas/as/astd/react.git"
              sh "git fetch"
              def gitTag = sh(script:"git tag -l ${inputTagVersion}", returnStdout:true).trim()
              if (gitTag.isEmpty()) {
                if (inputTagComment.isEmpty()) {
                  error('Please set non-empty environment variable TAG_COMMENT for creating new tag!')
                }
                echo ("Tag new version ${inputTagVersion} in master. (NOTHING TO DO for sample test of sonarqube only)")
/* sample test for sonarqube only, skip tag process */
/*
                sh("""
                  git pull origin master
                  git tag -a ${inputTagVersion} -m '${inputTagComment}'
                  git push origin ${inputTagVersion}
                """)
*/
              }
              else {
                echo ("Tag ${inputTagVersion} already exist. Will build from existing tag.")
              }
            }
          }
        }
      }
    }

    stage('Code Analysis') {
      steps {
        container("nodejs-container") {
          script {
            openshift.withCluster() {
              withCredentials([usernamePassword(credentialsId: "cicd-opaque-sonarqube-auth-secret", usernameVariable: "SONARQUBE_USER", passwordVariable: "SONARQUBE_PWD")]) {
                def var_ScannerHome = tool 'SonarQubeScanner'
                def var_SonarProjectKey = "${inputDevProject}-${config_Component}" // e.g. astd-react
                sh "${var_ScannerHome}/bin/sonar-scanner \
                -Dsonar.host.url=http://sonarqube:9000 \
                -Dsonar.token=${SONARQUBE_PWD} \
                -Dsonar.projectKey=${var_SonarProjectKey}"
              }
            }
          }
        }
      }
    }
  }
}
