import PlaceOutlinedIcon from '@mui/icons-material/PlaceOutlined';
import LocalShippingOutlinedIcon from '@mui/icons-material/LocalShippingOutlined';
import PortraitOutlinedIcon from '@mui/icons-material/PortraitOutlined';
import DescriptionOutlinedIcon from '@mui/icons-material/DescriptionOutlined';
import SearchIcon from '@mui/icons-material/Search';
import NotificationsNoneIcon from '@mui/icons-material/NotificationsNone';
import LanguageIcon from '@mui/icons-material/Language';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';
import FolderCopyIcon from '@mui/icons-material/FolderCopy';
import PersonAddIcon from '@mui/icons-material/PersonAdd';
import LocationOnIcon from '@mui/icons-material/LocationOn';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';

export const PLACE_ICON = PlaceOutlinedIcon;
export const SHIPPING_CAR_ICON = LocalShippingOutlinedIcon;
export const STAFF_ICON =  PortraitOutlinedIcon;
export const DOCUMENT_ICON = DescriptionOutlinedIcon;
export const SEARCH_ICON = SearchIcon;
export const NOTIFICATION_ICON = NotificationsNoneIcon;
export const LANGUAGE_ICON = LanguageIcon;
export const RIGHT_ARROW_ICON = ChevronRightIcon;
export const FOLDER_ICON = FolderCopyIcon;
export const ADD_PERSON_ICON = PersonAddIcon;
export const LOCATION_ICON = LocationOnIcon;
