apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: astd 
  name: account-pvc
  labels:
    name: account 
    owner: fhk
    component: api
    env: development
    version: v1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
